set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'ycm-core/YouCompleteMe'
Plugin 'fatih/vim-go'
Plugin 'mkitt/tabline.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'scrooloose/nerdcommenter'
Plugin 'kchmck/vim-coffee-script'
Plugin 'w0ng/vim-hybrid'
Plugin 'leafgarland/typescript-vim'
Plugin 'rust-lang/rust.vim'

" theme package
Plugin 'dracula/vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" global config
syntax enable
set backspace=2
set laststatus=2

" turn on color theme
" set background=dark
" let g:solarized_termcolors=256
" colorscheme solarized
colorscheme dracula
set termguicolors
"hi Normal guibg=NONE ctermbg=NONE

" Plugin Config
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

" airline
let g:airline_theme = "bubblegum"
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''

map <C-n> :NERDTreeToggle<cr>
cmap <C-n> :NERDTreeToggle<cr>
map <C-k> :NERDTreeFind<cr>
cmap <C-k> :NERDTreeFind<cr>

let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_function_calls = 1
let g:go_fmt_command = "goimports"

" my config
set nu
set cursorline cursorcolumn

" set tab size to 4 and 1 tab to 4 space
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent

" set mouse=a " set mouse enable

map <S-q> :tabp<cr>
map <S-w> :tabn<cr>

" react
let g:jsx_ext_required = 0
"let g:jsx_pragma_required = 1

set completeopt-=preview

" rust
let g:rustfmt_autosave = 1
